update=03/08/2009 16:48:41
last_client=pcbnew
[pcbnew]
version=1
PadDrlX=0
PadDimH=177
PadDimV=787
ViaDiam=310
ViaDril=200
ViaAltD=250
MViaDia=200
MViaDrl=80
Isol=80
Countlayer=2
Lpiste=150
RouteTo=15
RouteBo=0
TypeVia=3
Segm45=1
Racc45=1
SgPcb45=1
TxtPcbV=800
TxtPcbH=600
TxtModV=600
TxtModH=600
TxtModW=120
HPGLnum=1
HPGdiam=15
HPGLSpd=20
HPGLrec=2
HPGLorg=0
VEgarde=100
DrawLar=150
EdgeLar=150
TxtLar=120
MSegLar=100
WpenSer=10
[pcbnew/libraries]
LibDir=
LibName1=sockets
LibName2=D:/Ariel/Mis documentos/Facultad/Tesis/Placas/Controlador/Kicad/conn15_1mm_smd
LibName3=D:/Ariel/Mis documentos/Facultad/Tesis/Placas/Controlador/Kicad/tsop2_44
LibName4=D:/Ariel/Mis documentos/Facultad/Tesis/Placas/Controlador/Kicad/tqfp32
LibName5=D:/Ariel/Mis documentos/Facultad/Tesis/Placas/Controlador/Kicad/sw_push_small2
LibName6=D:/Ariel/Mis documentos/Facultad/Tesis/Placas/Controlador/Kicad/soj28
LibName7=D:/Ariel/Mis documentos/Facultad/Tesis/Placas/Controlador/Kicad/msop8
LibName8=D:/Ariel/Mis documentos/Facultad/Tesis/Placas/Controlador/Kicad/hc_osc
LibName9=D:/Ariel/Mis documentos/Facultad/Tesis/Placas/Controlador/Kicad/conn_5x2
LibName10=D:/Ariel/Mis documentos/Facultad/Tesis/Placas/Controlador/Kicad/conn_3x2
LibName11=connect
LibName12=discret
LibName13=pin_array
LibName14=divers
LibName15=libcms
LibName16=display
LibName17=valves
LibName18=led
LibName19=dip_sockets
